services:
  dude-api-app:
    container_name: dude-api-app
    build:
      dockerfile: dev.Dockerfile
      context: .
    networks:
      - dude-api
    ports:
      - "8080:8080"
      - "8081:8081"
    expose:
      - "8080"
      - "8081"
    volumes:
      - .:/app
    env_file:
      - .env

  dude-api-database:
    container_name: dude-api-database
    image: mysql:8
    restart: always
    networks:
      - dude-api
    volumes:
      - dude-api-database-data:/var/lib/mysql
    env_file:
      - .env

volumes:
  dude-api-database-data:
    driver: local

networks:
  dude-api:
    driver: bridge
